SERVER_IP: null
general:
  auto_open_qr_web_page: true
  local_ip_detect:
    host: 223.5.5.5
    port: 80
log_level: INFO
osc:
  listen_host: 127.0.0.1
  listen_port: 9001
osr2:
  com_port: COM6
  ema_filter: 0.9
  inserted_ass: /avatar/parameters/OGB/Orf/Ass/PenOthers
  inserted_pussy: /avatar/parameters/OGB/Orf/Pussy/PenOthers
  inserting_others: /avatar/parameters/OGB/Pen/*
  inserting_self: /avatar/parameters/OGB/Pen/*
  max_acceleration: 20000
  max_pos: 900
  max_velocity: 1500
  min_pos: 0
  objective: inserting_self
  updates_per_second: 50
  vrchat_max: 1000
  vrchat_min: 0
version: v0.1.1
web_server:
  listen_host: 127.0.0.1
  listen_port: 8800
ws:
  listen_host: 0.0.0.0
  listen_port: 28846
  master_uuid: aa4a1c84-8dd6-4512-8744-e2a0442dde7b
