osr2:
  com_port: COM3
  inserted:
  - /avatar/parameters/pcs/contact/enterPass
  - /avatar/parameters/Shock/TouchAreaA
  - /avatar/parameters/Shock/TouchAreaC
  - /avatar/parameters/Shock/wildcard/*
  inserting:
    others: /avatar/parameters/OGB/Pen/Dick/PenOthers
    self: /avatar/parameters/OGB/Pen/Dick/PenSelf
  interval: 0.1
  max_pos: 900
  min_pos: 100
  objective: self
  stroke_mode: linear
  user_type: inserting
version: v0.2.0
