SERVER_IP: null
general:
  auto_open_qr_web_page: true
  local_ip_detect:
    host: 223.5.5.5
    port: 80
log_level: INFO
osc:
  listen_host: 127.0.0.1
  listen_port: 9001
osr2:
  com_port: COM4
  inserted_ass: /avatar/parameters/OGB/Orf/Ass/PenOthers
  inserted_pussy: /avatar/parameters/OGB/Orf/Pussy/PenOthers
  inserting_others: /avatar/parameters/OGB/Pen/*
  inserting_self: /avatar/parameters/OGB/Pen/*
  max_pos: 900
  max_velocity: 1400
  min_pos: 100
  objective: inserting_others
  updates_per_second: 50
  vrchat_max: 1000
  vrchat_min: 0
version: v0.1.2
web_server:
  listen_host: 127.0.0.1
  listen_port: 8800
ws:
  listen_host: 0.0.0.0
  listen_port: 28846
  master_uuid: 700ce2a3-0cc4-446b-adea-0bbf18aadcbd
